#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders and links
mkdir -p /music /config/storage
if [ ! -d "/config/storage/framework" ] || [ ! -d "/config/storage/search-indexes" ]; then
  cp -r /var/www/html/storage/* /config/storage
fi
rm -rf /var/www/html/storage
ln -s /config/storage /var/www/html/storage
cp -f /defaults/mariadb-fix.php /var/www/html/database/migrations/2022_08_01_093952_use_uuids_for_song_ids.php

# permissions
lsiown abc:abc /music
lsiown -R abc:abc \
    /config \
    /var/www/html

chmod -R 775 /config/storage
